# Generated by Django 4.2.7 on 2024-01-20 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import farm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
            },
            managers=[
                ('objects', farm.models.CommodityManager()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_at', models.DateTimeField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_related', to='farm.commodity')),
                ('farmer_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produced_food', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food',
            },
        ),
    ]
